# Site settings
title: "Ashley Hart"
subtitle: "AI Researcher | Developer | Ph.D. Student"
description: "Chronologing my research journey."
url: "https://ashleybhart.com"
locale: "en-US"


# Theme settings
remote_theme: "mmistakes/minimal-mistakes"
plugins:
  - jekyll-remote-theme
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag

minimal_mistakes_skin: "dark" # "default", "air", "aqua", "contrast", "dark", "dirt", "neon", "mint", "plum", "sunrise"

# Add anything Jekyll needs to "see" below.
include: ["_pages"]


# Navigation
navigation:
  main: main


# Author info
author:
  name: "Ashley Hart"
  email: "ashley.hart@ufl.edu"
  github: ashley-hart
  avatar: "/assets/images/me.png"
  bio: "AI Researcher • Game Developer • Mentor"
  # location: "USA"
  email: "ashley.hart@ufl.edu"
  linkedin: "ashley-b-hart"
  github: "ashley-hart"
  # links:
    # - label: "Email"
    #   icon: "fas fa-envelope"
    #   url: "mailto:ashley.hart@ufl.edu
    # - label: "GitHub"
    #   icon: "fab fa-github"
    #   url: "https://github.com/ashley-hart"
    # - label: "LinkedIn"
    #   icon: "fab fa-linkedin"
    #   url: "https://linkedin.com/in/yourusername"
repository: "ashley-hart/ashley-hart.github.io"
logo: "/assets/images/temp-logo.png"
masthead_title: "Ashley Hart"

# Adding pages dir for visibility
# ["_pages"]


defaults: # for various aspects of the site
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      read_time: true
      comments: true
      share: true
      related: true
      author_profile: true
  # _pages
  - scope:
      path: ""
      type: pages
    values:
      layout: single
      author_profile: true


# Other options
paginate: 5

